### ISSUE TITLE
GHC 8.6.3 test run

### ISSUE THREAD

**Issue by jrp2014** [robstewart57/rdf4h#62]
Running `cabal -O2 new-build` and `cabal -O2 new-test --enable coverage` results in the following: 
[rdf4h-3.1.1-test-rdf4h.log](https://github.com/robstewart57/rdf4h/files/2788931/rdf4h-3.1.1-test-rdf4h.log)

**Comment by robstewart57** [comment]
@jrp2014 thanks.

This log shows many test failures for the `parser-w3c-tests-xml` group. This is due to the RDF/XML parser does not pass all W3C tests. See https://github.com/robstewart57/rdf4h/issues/17 .

I've made a start on reimplementing the RDF/XML parser using the parser combinators approach in xmlbf (rather than using arrows in the current hxt based implementation). The xmlbf branch:

https://github.com/robstewart57/rdf4h/tree/xmlbf

But progress has stalled for the time being. Feel free to take a look and attempt to complete the RDF/XML parser reimplementation :)

**Comment by wismill** [comment]
This issue will be fixed by #67 .

**Comment by robstewart57** [comment]
All rdf4h tests now pass with GHC 8.6:

https://travis-ci.org/robstewart57/rdf4h/jobs/631996838
